# Generated by Django 5.0.2 on 2024-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRSS', '0012_remove_fileupload_doc_file_fileupload_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='PPRSS/wmpnssui.dll.mui', upload_to='pefiles/'),
        ),
    ]
